<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Crescendo.Stoelenplan.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crescendo.Stoelenplan.Shared\Crescendo.Stoelenplan.Shared.csproj" />
  </ItemGroup>

</Project>
